### ISSUE TITLE
onClick event locks the pie chart

### ISSUE THREAD

**Issue by arpit7j** [vonbearshark/react-donut-chart#10]
Hi,

With the current version of the code, onClick event, lock down the pie chart untill user double click on same arc.
Is there any way to disable this lock without doing any change on library code. I meant by passing any props.

Thanks

**Comment by vonbearshark** [comment]
Hey @arpit7j,

What would you like the expected behavior to be? Right now hovering has the same effect as I think what you are looking for (highlighting the arc + corresponding list item), no? How should clicking be differentiated from hovering?

**Comment by arpit7j** [comment]
@vonbearshark  Issue is very simple. Once user click on any arc - it lock other arc to get hover or click event untill user click on same arc(which he/she clicked earlier).
Can you please add props if developer don't want to lock arc on click event.

**Comment by vonbearshark** [comment]
Yes, I understand. That is expected behavior right now. What do you want to do be able to do instead `onClick`? Nothing?

**Comment by arpit7j** [comment]
@vonbearshark  did you get my pain point..?

**Comment by vonbearshark** [comment]
Yes. I can probably take a look this weekend.

**Comment by arpit7j** [comment]
Thank You So Much.l really need it otherwise I need to look it for other options. I already integrated this is in my application and I don't want to move to other libraries. I hope you will figure out something and will push latest change.

**Comment by arpit7j** [comment]
Hi @vonbearshark .. can you please do the needful before the weekend. I need it on urgent basis. I would highly appreciate your effort.Thanks.

**Comment by vonbearshark** [comment]
Should be fixed with the `clickToggle` prop now, @arpit7j. Just released `1.1.6` on NPM with this.

**Comment by arpit7j** [comment]
@vonbearshark  that clickToggle prop work like charm. Nice work ! and Tons of thanks.

**Comment by vonbearshark** [comment]
Glad it worked out

**Comment by arpit7j** [comment]
open a new one :(

**Comment by vonbearshark** [comment]
No problem. I'll take a look when I can. Feel free to fork and sub a PR yourself if that is insufficient. I can point you in the right direction, if needed.
