### ISSUE TITLE
unable to customize

### ISSUE THREAD

**Issue by ggepenyan** [vonbearshark/react-donut-chart#14]
For example to increase or decrease font sizes, or size of the chart circle. Is it possible?
In my case categories are near each other, I'm not able to add white spaces between them. And I'm not able to change the font size of them, they are too small.
![screenshot](https://user-images.githubusercontent.com/17830568/39966181-404a8a6c-565c-11e8-9908-fd257dad9e53.png)

**Comment by vonbearshark** [comment]
It is not currently possible, but nothing is preventing it. What customizations would you be interested in, exactly? I don't know when I would be able to work on it myself, but I would be happy to work through, look over, and merge a pull request with you.

**Comment by ggepenyan** [comment]
ok, I will try to create a one if I have time. Actually I have no practice with creating a pull request )), but hope I'll do it and let you know about that

**Comment by ggepenyan** [comment]
ok, what I need to get is somethink like this.
![screenshot 7](https://user-images.githubusercontent.com/17830568/44309436-71c76d00-a37b-11e8-981e-d60d081a4c44.png)

I achieved it by changing the width prop of arcs and legend from `graphwidth` variable into `width` and adding `transform: "translate(x, y)"` to `group` elements (to arcs, innertext, legend). But it's not the best solution. If the height of the container chagnes, my transformations have to change also. And actually if new legend item is added, it will not be visible

**Comment by ggepenyan** [comment]
@vonbearshark, did you see the pull request?

**Comment by vonbearshark** [comment]
Hey yes sorry I was on vacation. Just left a comment there

**Comment by nehalb123** [comment]
@ggepenyan  How can I customize the legend? (aligning it with the chart)

**Comment by ggepenyan** [comment]
I started to think about changing the package already

**Comment by vonbearshark** [comment]
Sorry for the absence, all. I am going to close this issue, but I can keep talking through solutions. Based on the submitted PR, I do think this is already possible through `transform: translate` and the existing exposed classes
