### ISSUE TITLE
selectedOffset for innerRadius and other questions

### ISSUE THREAD

**Issue by realioseb** [vonbearshark/react-donut-chart#21]
Hello,

I have few questions but mostly I want to know how to change inner radius of a single item on hover.

1. I could change outer radius using `selectedOffset` prop but I want to change inner too. How can I achieve it?
2. I need a static `inner text`. It shouldn't be changing on item hover.
3. How can I change border width (or space between items)? I was able to change border color with `strokeColor` prop

You can see the picture of what I'm trying to achieve

![doughnut](https://user-images.githubusercontent.com/6136314/64011275-6c733580-cb2c-11e9-833b-cbea4b6aeff7.png)

**Comment by vonbearshark** [comment]
Unfortunately these are all additional features that I won't have time to add to this library. if you would like to add them yourself, I would be happy to review your PR.
