### ISSUE TITLE
Longer labels truncated automatically

### ISSUE THREAD

**Issue by karthikdivi** [vonbearshark/react-donut-chart#22]
Thanks for the great library, I am having issues with longer text labels. They are automatically truncated. Ideally, they should go to the next line. 
![](https://res.cloudinary.com/karthikdivi/image/upload/v1567333783/temp/Screenshot_2019-09-01_at_3.58.22_PM.png)
Replicated here  https://codesandbox.io/s/gracious-cori-hpyp7

**Comment by vonbearshark** [comment]
Ah. Yeah. Looks like a bug. I don't think I will have the time to fix, but I would be happy to review a PR if you wanted to fix it

**Comment by vonbearshark** [comment]
I'm sorry, but I am closing this as wontfix. I've investigated a couple of alternatives here, but the short answer is that this is surprisingly impracticable if this package wants to maintain its simplicity, lack of external deps, and browser support
