### ISSUE TITLE
data is not working

### ISSUE THREAD

**Issue by anil-hub** [vonbearshark/react-donut-chart#24]
current version -
data is not updated it is just showing the default value
also tried the data snippet in code- still not working

              <DonutChart
    data={[{
        label: 'Give you up',
        value: 25
    },
    {
        label: 'oiupi',
        value: 75,
        
    }]} />

<img width="477" alt="Capture" src="https://user-images.githubusercontent.com/55500872/76323391-a9ee2200-630a-11ea-8be5-208ed285dcea.PNG">

**Comment by blasterbug** [comment]
Same here, the developer seems to have abandoned the development/support.

**Comment by vonbearshark** [comment]
@blasterbug @anil-hub apologies. This should be fixed now per the latest version
