### ISSUE TITLE
warning message from Arcs component

### ISSUE THREAD

**Issue by mvolkmann** [vonbearshark/react-donut-chart#3]
I believe there is an issue with the following line in Arcs.js:
````
 key={ `arcpath${index}` }
````

I get the following in the browser console:

warning.js:36 Warning: ArcPath: `key` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop. (https://fb.me/react-special-props)

**Comment by vonbearshark** [comment]
Again, sorry for the delay. I should really watch my own repos. This should be fixed now
