### ISSUE TITLE
Peer dependency issue when installing package on react  17.0.2  project

### ISSUE THREAD

**Issue by Nikostito** [vonbearshark/react-donut-chart#31]
In your package.json file you have a peer depndency for react **16.3.0**.

Which means if you try to install your package to a new blank project of react 17.0.2 npm will give you a dependency issue error on installation.

**Comment by vonbearshark** [comment]
Can you confirm you are seeing that error and that it is from this package?

This `package.json` currently has

```
  "peerDependencies": {
    "react": "^16.3.0",
    "react-dom": "^16.3.0"
  },
 ```
 
 So, it should be **^** 16 (_greater_ than version 16), rather than _exactly_ `16.3.0`. The `devDependencies` even include `react` and `react-dom` at version `17.0.2`, and I just ran a fresh dev install without any errors.

**Comment by Nikostito** [comment]
Thanks for the quick reply.

This is what I try:
`npx create-react-app test`
`npm i`
`npm i --save react-donut-chart`
While installing I get this error:

    
    npm ERR! code ERESOLVE    
    npm ERR! ERESOLVE unable to resolve dependency tree
    npm ERR! 
    npm ERR! While resolving: test@0.1.0
    npm ERR! Found: react@17.0.2
    npm ERR! node_modules/react
    npm ERR!   react@"^17.0.2" from the root project
    npm ERR! 
    npm ERR! Could not resolve dependency:
    npm ERR! peer react@"^16.3.0" from react-donut-chart@1.2.1
    npm ERR! node_modules/react-donut-chart
    npm ERR!   react-donut-chart@"*" from the root project
    npm ERR! 
    npm ERR! Fix the upstream dependency conflict, or retry
    npm ERR! this command with --force, or --legacy-peer-deps
    npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by vonbearshark** [comment]
Ah, I think you are right. It seems like `>=` does what I thought `^` would do. I just pushed an update to the peer deps, and I am publishing now. lmk if it works (on version `1.2.2`).

**Comment by Nikostito** [comment]
Hey, yeah the issue is fixed now. Thanks for fixing package.json! Cheers :)
