### ISSUE TITLE
Module has some babel plugin issue

### ISSUE THREAD

**Issue by SabariGanesh-K** [vonbearshark/react-donut-chart#37]
![image](https://user-images.githubusercontent.com/64348740/182417861-b4b261bc-6186-4eb4-9325-5a775190b464.png)

**Comment by vonbearshark** [comment]
Could you say more about your local setup?

It looks like the package's Babel `dist` output is not compiling [the optional chaining syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) to an older standard. This package's Babel compilation target is based [on its `browserlist`](https://github.com/vonbearshark/react-donut-chart/blob/main/package.json#L53), which seems pretty fair as is support-wise. Open to updating it if it's reasonable, though.

**Comment by dcporter44** [comment]
+1

I use optional chaining throughout my app (created with CRA). But apparently it can't use optional chaining with dependencies.

This Stackoverflow answer explains the problem: https://stackoverflow.com/a/63423634/7629239

**Comment by vonbearshark** [comment]
Just published a latest version that should address the issues. Closing, but let me know if it does not
