### ISSUE TITLE
Module not found error

### ISSUE THREAD

**Issue by NicciWill-Solutions** [vonbearshark/react-donut-chart#9]
Hi @vonbearshark 

I'm getting this error in the browser:

_**./node_modules/react-donut-chart/lib/dist/Arcs.js**
**Module not found: Can't resolve 'classnames' in '.../node_modules/react-donut-chart/lib/dist'**_

**Comment by NicciWill-Solutions** [comment]
My bad, disregard. I just saw that I needed to install classnames.

**Comment by vonbearshark** [comment]
Sorry for the delay. Glad it worked out!

**Comment by NicciWill-Solutions** [comment]
@ggepenyan, you need to 'npm install classnames'

**Comment by vonbearshark** [comment]
You shouldn't have to, though. It's in both the `package.json` and `package-lock`. It should be pulled in automatically. I don't know why it's not.

**Comment by ggepenyan** [comment]
I think [#13](https://github.com/vonbearshark/react-donut-chart/issues/13#issuecomment-384067022) will fix it. Waiting for that

**Comment by vonbearshark** [comment]
Alright, I think I fixed everything. I just pushed to master. If someone wants to point to that for their install and let me know if it solves all of their issues, I can publish the patch.

**Comment by vonbearshark** [comment]
Just published fix 👍
